apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: booky
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080   # choose between 30000–32767
  type: NodePort
