apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: booky
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hristina123/backend-booky:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: booky-config

