apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: booky
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000   # you can pick between 30000–32767
  type: NodePort
